const ENDPOINT = 'https://script.google.com/macros/s/AKfycbwJ1U-tb2kXdLWRTRrOftsoFetnUHx-3-YkMv8uAccdN5Gy3BG54tNoIQzBKMGInAbHAg/exec';
let source = { 'Movimentação': [], Associado: [] };
let showingAllTransactions = false;
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const monthNames=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const fmt=v=>money.format(v||0), parseDate=v=>v?new Date(v):null;
function cleanMovements(){return (source['Movimentação']||[]).map((m,i)=>({...m,id:i,date:parseDate(m.Data),value:Number(m.Valor)||0})).filter(m=>m.date && !isNaN(m.date));}
function filters(){const movements=cleanMovements(), period=document.querySelector('#period-filter').value, category=document.querySelector('#category-filter').value, from=document.querySelector('#date-from').value, to=document.querySelector('#date-to').value;return movements.filter(m=>{const day=m.date.toISOString().slice(0,10);return (period==='all'||m.date.toISOString().slice(0,7)===period)&&(category==='all'||m.Classificação===category)&&(!from||day>=from)&&(!to||day<=to)})}
function render(){const all=cleanMovements(), rows=filters(), income=rows.filter(r=>r.value>0).reduce((a,r)=>a+r.value,0), expense=rows.filter(r=>r.value<0).reduce((a,r)=>a+r.value,0), balance=income+expense, associateSet=new Set(rows.filter(r=>r.Classificação==='Mensalidade'&&r.Associado).map(r=>r.Associado));
 document.querySelector('#balance').textContent=fmt(balance);document.querySelector('#income').textContent=fmt(income);document.querySelector('#expense').textContent=fmt(Math.abs(expense));document.querySelector('#associates-count').textContent=source.Associado?.filter(a=>a.Nome).length||0;
 document.querySelector('#balance-note').textContent=`${rows.length.toLocaleString('pt-BR')} lançamentos no período`;document.querySelector('#income-note').textContent=`${share(income,Math.abs(expense))}% sobre as saídas`;document.querySelector('#expense-note').textContent=`${rows.filter(r=>r.value<0).length} pagamentos realizados`;document.querySelector('#associates-note').textContent=`${associateSet.size} com mensalidade no período`;
 const months=lastMonths(rows,6); document.querySelector('#period-title').textContent=rows.length?`Dados de ${formatPeriod(rows)} · atualização em tempo real`:'Nenhum lançamento encontrado para os filtros selecionados';renderChart(rows,months);renderDistribution(rows,income);renderTransactions(rows);renderInsights(rows,income,expense,balance,associateSet);renderMembers(rows);renderTopExpenses(rows);
}
function share(a,b){return b?Math.round(a/b*100):0}function lastMonths(rows,n){const keys=[...new Set(rows.map(r=>r.date.toISOString().slice(0,7)))].sort();return keys.slice(-n)}function formatPeriod(rows){const ds=rows.map(r=>r.date).sort((a,b)=>a-b);return `${ds[0].toLocaleDateString('pt-BR',{month:'short',year:'numeric'})} a ${ds.at(-1).toLocaleDateString('pt-BR',{month:'short',year:'numeric'})}`}
function renderChart(rows,months){const values=months.map(k=>{const r=rows.filter(x=>x.date.toISOString().slice(0,7)===k);return {in:r.filter(x=>x.value>0).reduce((a,x)=>a+x.value,0),out:Math.abs(r.filter(x=>x.value<0).reduce((a,x)=>a+x.value,0))}}), max=Math.max(1,...values.flatMap(x=>[x.in,x.out]));document.querySelector('#bar-chart').innerHTML=months.map((k,i)=>`<div class="month" title="Entradas: ${fmt(values[i].in)} | Saídas: ${fmt(values[i].out)}"><div class="bar in" style="height:${Math.max(2,values[i].in/max*100)}%"></div><div class="bar out" style="height:${Math.max(2,values[i].out/max*100)}%"></div><label>${monthNames[Number(k.slice(5))-1]}</label></div>`).join('')||'<p class="empty">Sem dados para o gráfico.</p>'}
function renderDistribution(rows,income){const colors=['#356dff','#16a878','#e9a722','#8d63ff','#ea6f91'], groups=Object.entries(rows.filter(r=>r.value>0).reduce((o,r)=>{const k=r.Classificação||'Não classificado';o[k]=(o[k]||0)+r.value;return o},{})).sort((a,b)=>b[1]-a[1]).slice(0,5), top=groups[0]?.[1]||0;document.querySelector('#donut').style.setProperty('--angle',`${income?top/income*360:0}deg`);document.querySelector('#donut-value').textContent=fmt(income);document.querySelector('#distribution-list').innerHTML=groups.map(([name,value],i)=>`<li><i style="background:${colors[i]}"></i>${name}<b>${share(value,income)}%</b></li>`).join('')||'<li>Sem entradas no período</li>'}
function renderTransactions(rows){const button=document.querySelector('#show-all'), sorted=[...rows].sort((a,b)=>b.date-a.date), visible=showingAllTransactions?sorted:sorted.slice(0,6);button.textContent=showingAllTransactions?'Mostrar recentes ↑':`Ver todos${sorted.length>6?` (${sorted.length})`:''} →`;button.style.visibility=sorted.length>6?'visible':'hidden';document.querySelector('#transactions').innerHTML=visible.map(r=>`<tr><td>${r.date.toLocaleDateString('pt-BR')}</td><td title="${r.Associado||r['Nome responsável pelo Pix']||'—'}">${r.Associado||r['Nome responsável pelo Pix']||'—'}</td><td><span class="tag">${r.Classificação||'Não classificado'}</span></td><td>${r.Forma||r.Origem||'—'}</td><td class="amount ${r.value>=0?'positive':'negative'}">${r.value>=0?'+':'−'} ${fmt(Math.abs(r.value))}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma movimentação encontrada.</td></tr>'}
function renderInsights(rows,income,expense,balance,associateSet){const m=rows.filter(r=>r.Classificação==='Mensalidade'&&r.value>0).reduce((a,r)=>a+r.value,0), payments=Math.abs(rows.filter(r=>r.Classificação==='Pagamento').reduce((a,r)=>a+r.value,0));document.querySelector('#insights').innerHTML=`<div class="insight"><span>Mensalidades recebidas</span><strong>${fmt(m)}</strong></div><div class="insight"><span>Despesas classificadas como pagamento</span><strong>${fmt(payments)}</strong></div><div class="insight"><span>Resultado operacional</span><strong class="${balance>=0?'positive':'negative'}">${fmt(balance)}</strong></div>`}
function renderMembers(rows){const members=Object.entries(rows.filter(r=>r.Classificação==='Mensalidade'&&r.value>0&&r.Associado).reduce((o,r)=>{o[r.Associado]=(o[r.Associado]||0)+r.value;return o},{})).sort((a,b)=>b[1]-a[1]).slice(0,4);document.querySelector('#top-members').innerHTML=members.map(([name,value])=>`<div class="member"><span class="member-avatar">${name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><span class="member-name">${name}</span><span class="member-value">${fmt(value)}</span></div>`).join('')||'<small>Sem mensalidades no período.</small>'}
function renderTopExpenses(rows){const expenses=rows.filter(r=>r.value<0).sort((a,b)=>a.value-b.value).slice(0,10), total=Math.abs(expenses.reduce((sum,r)=>sum+r.value,0));document.querySelector('#expenses-total').textContent=expenses.length?`${fmt(total)} nos 10 maiores`:'Sem gastos no período';document.querySelector('#top-expenses').innerHTML=expenses.map((r,i)=>`<tr><td class="rank">${String(i+1).padStart(2,'0')}</td><td>${r.date.toLocaleDateString('pt-BR')}</td><td>${r.Associado||r['Nome responsável pelo Pix']||'—'}</td><td><span class="tag">${r.Classificação||'Não classificado'}</span></td><td>${r.Forma||r.Origem||'—'}</td><td class="amount negative">${fmt(Math.abs(r.value))}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma despesa encontrada para os filtros selecionados.</td></tr>'}
function populateFilters(){const rows=cleanMovements(), periods=[...new Set(rows.map(r=>r.date.toISOString().slice(0,7)))].sort().reverse(), cats=[...new Set(rows.map(r=>r.Classificação).filter(Boolean))].sort(), dates=rows.map(r=>r.date.toISOString().slice(0,10)).sort();document.querySelector('#period-filter').innerHTML='<option value="all">Todo o período</option>'+periods.map(p=>`<option value="${p}">${monthNames[Number(p.slice(5))-1]} ${p.slice(0,4)}</option>`).join('');document.querySelector('#category-filter').innerHTML='<option value="all">Todas</option>'+cats.map(c=>`<option>${c}</option>`).join('');document.querySelector('#date-from').min=dates[0];document.querySelector('#date-from').max=dates.at(-1);document.querySelector('#date-to').min=dates[0];document.querySelector('#date-to').max=dates.at(-1);document.querySelector('#associate-options').innerHTML=(source.Associado||[]).filter(a=>a.Nome).map(a=>`<option value="${a.Nome} — ${a.Registro}"></option>`).join('')}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim()}
function associateSearch(){const query=norm(document.querySelector('#associate-query').value.replace('—','-').split('-')[0]), target=document.querySelector('#associate-result');if(!query){target.innerHTML='<p>Informe um nome ou registro para consultar as mensalidades pagas.</p>';return}const people=(source.Associado||[]).filter(a=>norm(a.Nome).includes(query)||String(a.Registro||'').includes(query));if(!people.length){target.innerHTML='<p>Nenhum associado encontrado com essa pesquisa.</p>';return}const names=new Set(people.map(a=>norm(a.Nome))), rows=filters().filter(m=>m.Classificação==='Mensalidade'&&names.has(norm(m.Associado))).sort((a,b)=>b.date-a.date), total=rows.filter(r=>r.value>0).reduce((sum,r)=>sum+r.value,0);target.innerHTML=`<div class="associate-summary"><div><h4>${people.map(p=>p.Nome).join(' · ')}</h4><p>Registro: ${people.map(p=>p.Registro).join(' · ')} · ${rows.length} mensalidade(s) no período filtrado</p></div><div class="associate-total"><span>Total pago</span><strong>${fmt(total)}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Pagamento</th><th>Referência</th><th>Associado</th><th>Forma</th><th class="amount">Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date.toLocaleDateString('pt-BR')}</td><td>${r['Ref. Mês']&&r['Ref. Ano']?`${monthNames[Number(r['Ref. Mês'])-1]}/${r['Ref. Ano']}`:'—'}</td><td>${r.Associado}</td><td>${r.Forma||r.Origem||'—'}</td><td class="amount positive">${fmt(r.value)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma mensalidade paga no período selecionado.</td></tr>'}</tbody></table></div>`}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function load(){document.querySelector('#refresh').classList.add('spinning');try{const response=await fetch(ENDPOINT);if(!response.ok)throw Error();source=await response.json();populateFilters();render();document.querySelector('#updated-at').textContent='Atualizado agora';toast('Dados atualizados com sucesso.')}catch(e){toast('Não foi possível atualizar os dados. Tente novamente.');console.error(e)}finally{document.querySelector('#refresh').classList.remove('spinning')}}
document.querySelectorAll('select,input[type="date"]').forEach(e=>e.addEventListener('change',()=>{showingAllTransactions=false;render();associateSearch()}));document.querySelector('#clear-filters').onclick=()=>{document.querySelector('#period-filter').value='all';document.querySelector('#category-filter').value='all';document.querySelector('#date-from').value='';document.querySelector('#date-to').value='';showingAllTransactions=false;render();associateSearch()};document.querySelector('#refresh').onclick=load;document.querySelector('#show-all').onclick=()=>{showingAllTransactions=!showingAllTransactions;renderTransactions(filters())};document.querySelector('#associate-query').addEventListener('input',associateSearch);document.querySelector('#associate-clear').onclick=()=>{document.querySelector('#associate-query').value='';associateSearch()};document.querySelectorAll('nav a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const section=document.querySelector(link.getAttribute('href'));if(!section)return;section.scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('nav a').forEach(item=>item.classList.remove('active'));link.classList.add('active');history.replaceState(null,'',link.getAttribute('href'));toast(`Seção ${link.textContent.trim()} selecionada.`)}));load();
