const ENDPOINT='https://script.google.com/macros/s/AKfycbwJ1U-tb2kXdLWRTRrOftsoFetnUHx-3-YkMv8uAccdN5Gy3BG54tNoIQzBKMGInAbHAg/exec';
const monthNames=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});let source={'Movimentação':[],Associado:[]};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const isoDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function setCurrentMonth(force=false){const now=new Date(),from=document.querySelector('#date-from'),to=document.querySelector('#date-to');if(force||!from.value)from.value=isoDate(new Date(now.getFullYear(),now.getMonth(),1));if(force||!to.value)to.value=isoDate(new Date(now.getFullYear(),now.getMonth()+1,0))}
function movements(){return(source['Movimentação']||[]).map(m=>({...m,date:m.Data?new Date(m.Data):null,value:Number(m.Valor)||0})).filter(m=>m.date&&!isNaN(m.date)&&m.Classificação==='Mensalidade'&&m.value>0)}
function renderSearch(){const raw=document.querySelector('#associate-query').value,query=norm(raw.replace('—','-').split('-')[0]),target=document.querySelector('#associate-result');if(!query){target.innerHTML='<p>Informe um nome ou registro para consultar as mensalidades pagas.</p>';return}const people=(source.Associado||[]).filter(a=>norm(a.Nome).includes(query)||String(a.Registro||'').includes(query));if(!people.length){target.innerHTML='<p>Nenhum associado encontrado com essa pesquisa.</p>';return}const names=new Set(people.map(p=>norm(p.Nome))),from=document.querySelector('#date-from').value,to=document.querySelector('#date-to').value,rows=movements().filter(m=>{const day=m.date.toISOString().slice(0,10);return names.has(norm(m.Associado))&&(!from||day>=from)&&(!to||day<=to)}).sort((a,b)=>b.date-a.date),total=rows.reduce((sum,m)=>sum+m.value,0);target.innerHTML=`<div class="associate-summary"><div><h4>${people.map(p=>p.Nome).join(' · ')}</h4><p>Registro: ${people.map(p=>p.Registro).join(' · ')} · ${rows.length} mensalidade(s) no período</p></div><div class="associate-total"><span>Total pago</span><strong>${money.format(total)}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Pagamento</th><th>Referência</th><th>Associado</th><th>Forma</th><th class="amount">Valor</th></tr></thead><tbody>${rows.map(m=>`<tr><td>${m.date.toLocaleDateString('pt-BR')}</td><td>${m['Ref. Mês']&&m['Ref. Ano']?`${monthNames[Number(m['Ref. Mês'])-1]}/${m['Ref. Ano']}`:'—'}</td><td>${m.Associado}</td><td>${m.Forma||m.Origem||'—'}</td><td class="amount positive">${money.format(m.value)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma mensalidade paga no período selecionado.</td></tr>'}</tbody></table></div>`}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function load(){document.querySelector('#refresh').classList.add('spinning');try{const response=await fetch(ENDPOINT);if(!response.ok)throw Error();source=await response.json();document.querySelector('#associate-options').innerHTML=(source.Associado||[]).filter(a=>a.Nome).map(a=>`<option value="${a.Nome} — ${a.Registro}"></option>`).join('');setCurrentMonth();document.querySelector('#updated-at').textContent='Atualizado agora';renderSearch()}catch(error){toast('Não foi possível atualizar os dados. Tente novamente.');console.error(error)}finally{document.querySelector('#refresh').classList.remove('spinning')}}
document.querySelector('#associate-query').addEventListener('input',renderSearch);document.querySelectorAll('input[type="date"]').forEach(input=>input.addEventListener('change',renderSearch));document.querySelector('#associate-clear').onclick=()=>{document.querySelector('#associate-query').value='';renderSearch()};document.querySelector('#clear-dates').onclick=()=>{setCurrentMonth(true);renderSearch()};document.querySelector('#refresh').onclick=load;const gate=document.querySelector('#access-gate'),form=document.querySelector('#access-form'),password=document.querySelector('#access-password'),error=document.querySelector('#access-error');function grant(){gate.remove();load()}form.addEventListener('submit',event=>{event.preventDefault();if(password.value==='0148'){sessionStorage.setItem('gec-access','granted');grant()}else{error.textContent='Senha incorreta. Tente novamente.';password.select()}});if(sessionStorage.getItem('gec-access')==='granted')grant();
