const ENDPOINT='https://script.google.com/macros/s/AKfycbwJ1U-tb2kXdLWRTRrOftsoFetnUHx-3-YkMv8uAccdN5Gy3BG54tNoIQzBKMGInAbHAg/exec';
const monthNames=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});let source={'Movimentação':[],Associado:[]};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
function payments(){return(source['Movimentação']||[]).map(m=>({...m,value:Number(m.Valor)||0,month:Number(m['Ref. Mês']),year:Number(m['Ref. Ano'])})).filter(m=>m.Classificação==='Mensalidade'&&m.value>0&&m.Associado&&m.month>=1&&m.month<=12&&m.year)}
function populateYears(){const years=[...new Set(payments().map(p=>p.year))].sort((a,b)=>b-a);document.querySelector('#year-filter').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('')||'<option>Sem dados</option>'}
function render(){const year=Number(document.querySelector('#year-filter').value), rows=payments().filter(p=>p.year===year), byName=new Map();rows.forEach(p=>{const key=norm(p.Associado);if(!byName.has(key))byName.set(key,{name:p.Associado,months:Array(12).fill(0),count:0});const item=byName.get(key);item.months[p.month-1]+=p.value;item.count++});const members=[...byName.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));document.querySelector('#paid-members').textContent=members.length;document.querySelector('#payment-count').textContent=rows.length;document.querySelector('#received-total').textContent=money.format(rows.reduce((s,p)=>s+p.value,0));document.querySelector('#monthly-head').innerHTML=`<tr><th>Associado</th>${monthNames.map(m=>`<th>${m}</th>`).join('')}<th>Total</th></tr>`;const monthTotals=Array(12).fill(0);members.forEach(m=>m.months.forEach((v,i)=>monthTotals[i]+=v));document.querySelector('#monthly-body').innerHTML=members.length?members.map(member=>{const total=member.months.reduce((a,v)=>a+v,0);return `<tr><td>${member.name}</td>${member.months.map(v=>`<td class="${v?'paid':''}">${v?money.format(v):'—'}</td>`).join('')}<td class="total-column">${money.format(total)}</td></tr>`}).join('')+`<tr class="monthly-total"><td>Total recebido</td>${monthTotals.map(v=>`<td>${money.format(v)}</td>`).join('')}<td>${money.format(monthTotals.reduce((a,v)=>a+v,0))}</td></tr>`:'<tr><td class="monthly-empty" colspan="14">Nenhuma mensalidade paga com referência em '+year+'.</td></tr>'}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
async function load(){document.querySelector('#refresh').classList.add('spinning');try{const response=await fetch(ENDPOINT);if(!response.ok)throw Error();source=await response.json();populateYears();render();document.querySelector('#updated-at').textContent='Atualizado agora'}catch(error){toast('Não foi possível atualizar os dados. Tente novamente.');console.error(error)}finally{document.querySelector('#refresh').classList.remove('spinning')}}
document.querySelector('#year-filter').addEventListener('change',render);document.querySelector('#refresh').addEventListener('click',load);const gate=document.querySelector('#access-gate'),form=document.querySelector('#access-form'),password=document.querySelector('#access-password'),error=document.querySelector('#access-error');function grant(){gate.remove();load()}form.addEventListener('submit',event=>{event.preventDefault();if(password.value==='0148'){sessionStorage.setItem('gec-access','granted');grant()}else{error.textContent='Senha incorreta. Tente novamente.';password.select()}});if(sessionStorage.getItem('gec-access')==='granted')grant();
