const ENDPOINT='https://script.google.com/macros/s/AKfycbwJ1U-tb2kXdLWRTRrOftsoFetnUHx-3-YkMv8uAccdN5Gy3BG54tNoIQzBKMGInAbHAg/exec';
const monthNames=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});let source={'Movimentação':[],Associado:[]};
const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
function monthlyPayments(){return(source['Movimentação']||[]).map(m=>({...m,value:Number(m.Valor)||0,month:Number(m['Ref. Mês']),year:Number(m['Ref. Ano'])})).filter(m=>m.Classificação==='Mensalidade'&&m.value>0&&m.Associado&&m.month>=1&&m.month<=12&&m.year)}
function memberList(){const entries=new Map();(source.Associado||[]).filter(a=>a.Nome).forEach(a=>entries.set(norm(a.Nome),{name:a.Nome,registration:a.Registro||''}));monthlyPayments().forEach(m=>{if(!entries.has(norm(m.Associado)))entries.set(norm(m.Associado),{name:m.Associado,registration:''})});return[...entries.entries()].sort((a,b)=>a[1].name.localeCompare(b[1].name,'pt-BR'))}
function populateMembers(){document.querySelector('#member-options').innerHTML=memberList().map(([,member])=>`<option value="${member.name}${member.registration?` — ${member.registration}`:''}"></option>`).join('')}
function range(){const today=new Date(),months=[];for(let offset=-11;offset<=6;offset++){const date=new Date(today.getFullYear(),today.getMonth()+offset,1);months.push({month:date.getMonth()+1,year:date.getFullYear(),offset})}return months}
function selectedMember(){const raw=document.querySelector('#member-search').value.trim();if(!raw)return null;const namePart=raw.split('—')[0].trim(),query=norm(namePart),members=memberList();return members.find(([key,member])=>key===query||String(member.registration)===raw||String(member.registration)===namePart)||members.find(([key,member])=>key.includes(query)||String(member.registration).includes(raw))}
function render(){const selected=selectedMember(),timeline=document.querySelector('#timeline'),summary=document.querySelector('#situation-summary');if(!selected){timeline.innerHTML='<p class="empty-state">Pesquise e selecione um associado para visualizar a situação.</p>';summary.innerHTML='';return}const memberKey=selected[0],values=new Map();monthlyPayments().filter(m=>norm(m.Associado)===memberKey).forEach(m=>{const key=`${m.year}-${m.month}`;values.set(key,(values.get(key)||0)+m.value)});const months=range().map(item=>({...item,value:values.get(`${item.year}-${item.month}`)||0})),paid=months.filter(m=>m.value>0),late=months.filter(m=>m.offset<0&&!m.value&&m.month!==1),planned=months.filter(m=>m.offset>0&&!m.value&&m.month!==1),open=months.filter(m=>m.offset===0&&!m.value&&m.month!==1);summary.innerHTML=`<article><span>Meses pagos no período</span><strong>${paid.length} de ${months.length}</strong></article><article><span>Mensalidades em atraso</span><strong class="negative">${late.length}</strong></article><article><span>Próximas mensalidades pendentes</span><strong>${planned.length+(open.length?1:0)}</strong></article>`;timeline.innerHTML=months.map(item=>{const status=item.value>0?{text:'Pago',className:'paid'}:item.month===1?{text:'Cortesia',className:'courtesy'}:item.offset<0?{text:'Atrasado',className:'late'}:item.offset===0?{text:'Em aberto',className:'open'}:{text:'Futuro',className:'future'};return `<article class="month-status"><span class="year">${item.year}</span><h4>${monthNames[item.month-1]}</h4><span class="status-pill status-${status.className}">${status.text}</span>${item.value?`<p class="value">${money.format(item.value)}</p>`:status.className==='courtesy'?'<p class="value">Isento</p>':'<p class="value">—</p>'}</article>`}).join('')}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function load(){document.querySelector('#refresh').classList.add('spinning');try{const response=await fetch(ENDPOINT);if(!response.ok)throw Error();source=await response.json();populateMembers();document.querySelector('#updated-at').textContent='Atualizado agora';render()}catch(error){toast('Não foi possível atualizar os dados. Tente novamente.');console.error(error)}finally{document.querySelector('#refresh').classList.remove('spinning')}}
document.querySelector('#member-search').addEventListener('input',render);document.querySelector('#member-clear').addEventListener('click',()=>{document.querySelector('#member-search').value='';render()});document.querySelector('#refresh').addEventListener('click',load);const gate=document.querySelector('#access-gate'),form=document.querySelector('#access-form'),password=document.querySelector('#access-password'),error=document.querySelector('#access-error');function grant(){gate.remove();load()}form.addEventListener('submit',event=>{event.preventDefault();if(password.value==='0148'){sessionStorage.setItem('gec-access','granted');grant()}else{error.textContent='Senha incorreta. Tente novamente.';password.select()}});if(sessionStorage.getItem('gec-access')==='granted')grant();
